# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 377fe421a8466582ddcaa2c7b30cb5ad8bd0a04c116f860d543f35ae9c04fc475d74a733a8ee27af24822597347ffac079bc4c13b6a10663988cec7de49140e7

test:
  secret_key_base: 1919e3facce4684112ec2c28f09cc9c34ced711f9d0d270e4a39b238dfcd9968a2e53a14b595516562ff5da581d4ac2e1504bb9cd0aa0df677f50b0302a7a984

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
